name: Build and Push Docker image to ECR

on:
  push:
    branches:
      - main  # or change to your deployment branch

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ECR_LOGIN_URI: ${{ secrets.AWS_ECR_LOGIN_URI }}
      ECR_REPOSITORY_NAME: ${{ secrets.ECR_REPOSITORY_NAME }}
      IMAGE_TAG: latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        run: |
          echo "Building Docker image..."
          docker buildx create --use || true
          docker buildx build . \
            --platform linux/amd64 \
            --tag $AWS_ECR_LOGIN_URI/${ECR_REPOSITORY_NAME}:${IMAGE_TAG} \
            --push
          echo "Pushed image: $AWS_ECR_LOGIN_URI/${ECR_REPOSITORY_NAME}:${IMAGE_TAG}"
